version: "3"
services:
  mysql:
    container_name: mysql_db
    image: mysql
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: qna
      MYSQL_ROOT_PASSWORD: 924498
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d # MySQL 설정 파일 위치
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    networks:
      - test_network

  springbootapp:
    restart: on-failure
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/qna?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "924498"
    depends_on:
      - mysql
    networks:
      - test_network

networks:
  test_network:
