spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qna?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 924498
  thymeleaf:
    cache: false

  jpa:
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL57Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

  web:
    resources:
      add-mappings: false

logging:
  level:
    org:
      hibernate:
        type: trace
